#pragma config(Sensor, in1,    mobilePot,      sensorPotentiometer)
#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  LIFT_RIGHT_ENCODER, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  DRIVETRAIN_RIGHT_ENCODER, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  DRIVETRAIN_LEFT_ENCODER, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LIFT_LEFT_ENCODER, sensorQuadEncoder)
#pragma config(Motor,  port1,           rightDrive2,   tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           mobileIntake,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rollerClaw,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          leftDrive2,    tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "Drivetrain.c"
#include "MobileIntake.c"
#include "Lift.c"
#include "Armc.c"
#include "Claw.c"
#include "LCD.c"
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	clearLCDLine(0);
	clearLCDLine(1);
	startTask(autonomousLCD);

	//SET GYRO SENSOR
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	SensorType[in8] = sensorGyro;
	SensorValue[in8] = 0;
	wait1Msec(2000);

	SensorScale[in8] = 260;
	SensorFullCount[in8] = 3600;

	SensorValue(LIFT_LEFT_ENCODER) = 0;
	SensorValue(LIFT_RIGHT_ENCODER) = 0;
	SensorValue(DRIVETRAIN_RIGHT_ENCODER) = 0;
	SensorValue(DRIVETRAIN_LEFT_ENCODER) = 0;
	//REMEMBER TO SET UP ALL ENCODERS

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task autonomous()
{
	if(direction == 0){
		//24 POINT - LEFT
		motor[rollerClaw] = 30;
		setLift(15);
		wait1Msec(100);
		motor[mobileIntake] = 127;
		wait1Msec(700);
		moveForward(1400);
		motor[mobileIntake] = -127;
		wait1Msec(1300);
		motor[mobileIntake] = 0;
		setLift(10);
		outtake();
		wait1Msec(100);
		//moveForward(150);
		//intake();
		//downArm();
		//setLift(3);
		//wait1Msec(300);
		//setLift(10);
		//upArm();
		//outtake();
		setLift(20);
		moveBackward(1250);
		rotateLeft(160);
		moveBackward(550);
		rotateLeft(400);
		motor[rightDrive] = 127;
		motor[leftDrive] = 127;
		motor[mobileIntake] = 127;
		wait1Msec(1500);
		motor[rightDrive] = -127;
		motor[leftDrive] = -127;
		motor[mobileIntake] = -127;
		wait1Msec(1000);
		motor[mobileIntake] = 0;
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;
	}
	else if(direction == 1){
		//24 POINT - RIGHT
		motor[rollerClaw] = 30;
		setLift(15);
		wait1Msec(100);
		motor[mobileIntake] = 127;
		wait1Msec(700);
		moveForward(1400);
		motor[mobileIntake] = -127;
		wait1Msec(1300);
		motor[mobileIntake] = 0;
		setLift(10);
		outtake();
		wait1Msec(100);
		//moveForward(150);
		//intake();
		//downArm();
		//setLift(3);
		//wait1Msec(300);
		//setLift(10);
		//upArm();
		//outtake();
		setLift(20);
		moveBackward(1250);
		rotateRight(160);
		moveBackward(550);
		rotateRight(400);
		motor[rightDrive] = 127;
		motor[leftDrive] = 127;
		motor[mobileIntake] = 127;
		wait1Msec(1500);
		motor[rightDrive] = -127;
		motor[leftDrive] = -127;
		motor[mobileIntake] = -127;
		wait1Msec(1000);
		motor[mobileIntake] = 0;
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;
	}
	else if(direction == 2){
		//14 POINT - LEFT
		motor[rollerClaw] = 30;
		setLift(15);
		wait1Msec(100);
		motor[mobileIntake] = 127;
		wait1Msec(700);
		moveForward(1400);
		motor[mobileIntake] = -127;
		wait1Msec(1300);
		motor[mobileIntake] = 0;
		setLift(10);
		outtake();
		wait1Msec(100);
		moveForward(150);
		intake();
		downArm();
		setLift(3);
		wait1Msec(300);
		setLift(10);
		upArm();
		outtake();
		moveBackward(1400);
		rotateLeft(160);
		moveBackward(200);
		rotateLeft(340);
		moveForward(200);
		setLift(20);
		motor[mobileIntake] = 127;
		wait1Msec(1200);
		motor[mobileIntake] = 0;
		moveBackward(300);
	}
	else if(direction == 3){
		//14 POINT - RIGHT
		motor[rollerClaw] = 30;
		setLift(15);
		wait1Msec(100);
		motor[mobileIntake] = 127;
		wait1Msec(700);
		moveForward(1400);
		motor[mobileIntake] = -127;
		wait1Msec(1300);
		motor[mobileIntake] = 0;
		setLift(10);
		outtake();
		wait1Msec(100);
		moveForward(150);
		intake();
		downArm();
		setLift(3);
		wait1Msec(300);
		setLift(10);
		upArm();
		outtake();
		moveBackward(1400);
		rotateRight(160);
		moveBackward(200);
		rotateRight(340);
		moveForward(200);
		setLift(20);
		motor[mobileIntake] = 127;
		wait1Msec(1200);
		motor[mobileIntake] = 0;
		moveBackward(300);
	}
	else if(direction == 4){
		//9 POINT - LEFT
		motor[rollerClaw] = 30;
		setLift(15);
		wait1Msec(100);
		motor[mobileIntake] = 127;
		wait1Msec(700);
		moveForward(1400);
		motor[mobileIntake] = -127;
		wait1Msec(1300);
		motor[mobileIntake] = 0;
		setLift(10);
		outtake();
		wait1Msec(100);
		moveForward(150);
		intake();
		downArm();
		setLift(3);
		wait1Msec(300);
		setLift(10);
		upArm();
		outtake();
		moveBackward(1400);
		rotateLeft(160);
		moveBackward(50);
		rotateLeft(340);
		moveBackward(100);
		moveMobileIntake();
		moveBackward(300);
	}
	else if(direction == 5){
		//9	POINT RIGHT
		motor[rollerClaw] = 30;
		setLift(15);
		wait1Msec(100);
		motor[mobileIntake] = 127;
		wait1Msec(700);
		moveForward(1400);
		motor[mobileIntake] = -127;
		wait1Msec(1300);
		motor[mobileIntake] = 0;
		setLift(10);
		outtake();
		wait1Msec(100);
		moveForward(150);
		intake();
		downArm();
		setLift(3);
		wait1Msec(300);
		setLift(10);
		upArm();
		outtake();
		moveBackward(1400);
		rotateRight(160);
		moveBackward(50);
		rotateRight(340);
		moveBackward(100);
		moveMobileIntake();
		moveBackward(300);

	}
	else if(direction == 6){
		//SB+MB LEFT
		intake();
		downArm();
		setLift(95);
		slowMove(500);
		outtake();
		moveBackward(100);
		setLift(45);
		slowLeft(200);
		moveForward(500);
		setLift(25);
		slaveMotor(leftArm, rightArm);
		motor[rightArm] = 120;
		moveBackward(300);
		motor[rightLift] = -110;
		motor[leftLift] = -110;
		moveBackward(400);
		motor[rightArm] = 0;
		motor[rightLift] = 0;
		motor[leftLift] =0;
		rotateRight(600);
		moveBackward(600);
	}
	else if(direction == 7){
		//SB+MB RIGHT
		intake();
		downArm();
		setLift(95);
		slowMove(500);
		outtake();
		moveBackward(100);
		setLift(45);
		slowRight(200);
		moveForward(500);
		setLift(25);
		slaveMotor(leftArm, rightArm);
		motor[rightArm] = 120;
		moveBackward(300);
		motor[rightLift] = -110;
		motor[leftLift] = -110;
		moveBackward(400);
		motor[rightArm] = 0;
		motor[rightLift] = 0;
		motor[leftLift] =0;
		rotateLeft(600);
		moveBackward(600);
	}
	else if(direction == 8){
		//RAM
		motor[rightDrive] = -127;
		motor[leftDrive] = -127;
		wait1Msec(3000);
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;
	}
	else if(direction == 9){
		//DO NOTHING
		wait1Msec(5000);
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	startTask(NORMAL_DRIVE);
	startTask(MOBILE_GOAL_INTAKE);
	startTask(LIFT);
	startTask(ARM);
	startTask(CLAW);
	while (true)
	{
		continue;
	}
}
